// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCRIPTREQCHILD_NSCRIPTHOOK_H_
#define FLATBUFFERS_GENERATED_SCRIPTREQCHILD_NSCRIPTHOOK_H_

#include "flatbuffers/flatbuffers.h"

namespace NScriptHook {

struct FReqChild;

struct FReqChild FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODEMASK = 4
  };
  const flatbuffers::Vector<int32_t> *NodeMask() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_NODEMASK);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODEMASK) &&
           verifier.VerifyVector(NodeMask()) &&
           verifier.EndTable();
  }
};

struct FReqChildBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_NodeMask(flatbuffers::Offset<flatbuffers::Vector<int32_t>> NodeMask) {
    fbb_.AddOffset(FReqChild::VT_NODEMASK, NodeMask);
  }
  explicit FReqChildBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FReqChildBuilder &operator=(const FReqChildBuilder &);
  flatbuffers::Offset<FReqChild> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FReqChild>(end);
    return o;
  }
};

inline flatbuffers::Offset<FReqChild> CreateFReqChild(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> NodeMask = 0) {
  FReqChildBuilder builder_(_fbb);
  builder_.add_NodeMask(NodeMask);
  return builder_.Finish();
}

inline flatbuffers::Offset<FReqChild> CreateFReqChildDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *NodeMask = nullptr) {
  auto NodeMask__ = NodeMask ? _fbb.CreateVector<int32_t>(*NodeMask) : 0;
  return NScriptHook::CreateFReqChild(
      _fbb,
      NodeMask__);
}

inline const NScriptHook::FReqChild *GetFReqChild(const void *buf) {
  return flatbuffers::GetRoot<NScriptHook::FReqChild>(buf);
}

inline const NScriptHook::FReqChild *GetSizePrefixedFReqChild(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<NScriptHook::FReqChild>(buf);
}

inline bool VerifyFReqChildBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<NScriptHook::FReqChild>(nullptr);
}

inline bool VerifySizePrefixedFReqChildBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<NScriptHook::FReqChild>(nullptr);
}

inline void FinishFReqChildBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<NScriptHook::FReqChild> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFReqChildBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<NScriptHook::FReqChild> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NScriptHook

#endif  // FLATBUFFERS_GENERATED_SCRIPTREQCHILD_NSCRIPTHOOK_H_
