// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCRIPTSTACKVARS_NSCRIPTHOOK_H_
#define FLATBUFFERS_GENERATED_SCRIPTSTACKVARS_NSCRIPTHOOK_H_

#include "flatbuffers/flatbuffers.h"

#include "ScriptVarNode.h"

namespace NScriptHook {

struct FStackVars;

struct FStackVars FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VARLIST = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<FVarNode>> *VarList() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<FVarNode>> *>(VT_VARLIST);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VARLIST) &&
           verifier.VerifyVector(VarList()) &&
           verifier.VerifyVectorOfTables(VarList()) &&
           verifier.EndTable();
  }
};

struct FStackVarsBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_VarList(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<FVarNode>>> VarList) {
    fbb_.AddOffset(FStackVars::VT_VARLIST, VarList);
  }
  explicit FStackVarsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FStackVarsBuilder &operator=(const FStackVarsBuilder &);
  flatbuffers::Offset<FStackVars> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FStackVars>(end);
    return o;
  }
};

inline flatbuffers::Offset<FStackVars> CreateFStackVars(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<FVarNode>>> VarList = 0) {
  FStackVarsBuilder builder_(_fbb);
  builder_.add_VarList(VarList);
  return builder_.Finish();
}

inline flatbuffers::Offset<FStackVars> CreateFStackVarsDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<FVarNode>> *VarList = nullptr) {
  auto VarList__ = VarList ? _fbb.CreateVector<flatbuffers::Offset<FVarNode>>(*VarList) : 0;
  return NScriptHook::CreateFStackVars(
      _fbb,
      VarList__);
}

inline const NScriptHook::FStackVars *GetFStackVars(const void *buf) {
  return flatbuffers::GetRoot<NScriptHook::FStackVars>(buf);
}

inline const NScriptHook::FStackVars *GetSizePrefixedFStackVars(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<NScriptHook::FStackVars>(buf);
}

inline bool VerifyFStackVarsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<NScriptHook::FStackVars>(nullptr);
}

inline bool VerifySizePrefixedFStackVarsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<NScriptHook::FStackVars>(nullptr);
}

inline void FinishFStackVarsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<NScriptHook::FStackVars> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFStackVarsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<NScriptHook::FStackVars> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NScriptHook

#endif  // FLATBUFFERS_GENERATED_SCRIPTSTACKVARS_NSCRIPTHOOK_H_
